### PR TITLE
Fix duplicated cookie entries in http request

### PR DESCRIPTION
**Pull request by kezhuw**
Second overloading method `HttpMessageContentBuilder.buildMessageContent` uses
`HttpMessage.setCookies` to set cookies for message derived from
template without clearing old cookies from template.

This merge request fixes this by clearing old cookies in
`HttpMessage.setCookies`.

Feel free to reject this merge request if semantics change of `HttpMessage.setCookies` is harmful. Or should I degrade this merge request to an issue report ?

PS: I found only one usage of `HttpMessage.setCookies` in `HttpMessageController.handleRequestInternal` and didn't saw the harmness.

### CODE REVIEW

**Comment by svettwer** [comment]
Hi!

Thx for your suggestion. +1
Did you experience any problem with the current implementation? If so, it would be great if you could open an issue for that so that we've a little bit more context about the change.

BR,
Sven

**Comment by kezhuw** [comment]
@svettwer Due to #561, I can't present you a real example since #561 discard all cookie entries except the last. I find this non-happening issue in debugging of #561.

```java
public class HttpMessageContentBuilder extends AbstractMessageContentBuilder {
    public Message buildMessageContent(final TestContext context, final String messageType, final MessageDirection direction) {
        //Copy the initial message, so that it is not manipulated during the test.
        final HttpMessage message = new HttpMessage(template);

        delegate.getMessageHeaders().putAll(template.getHeaders());
        final Message constructed = delegate.buildMessageContent(context, messageType, direction);

        message.setName(delegate.getMessageName());
        message.setPayload(constructed.getPayload());
        message.setCookies(constructCookies(context));
        replaceHeaders(constructed, message);

        return message;
    }
}
```

`message.setCookies(constructCookies(context))` adds dynamic content replaced cookies to message which was derived from template with raw cookies.

**Comment by svettwer** [comment]
Hi!

Thx for the explanation. I'll have a look after #543 and #563 are merged.

BR,
Sven

**Comment by svettwer** [comment]
Hi!

I've created #569 concerning this issue.
I'll review the change, add tests and documentation followed by an internal PR.

BR,
Sven

**Comment by kezhuw** [comment]
@svettwer Thanks for your continuing complementary work on this deficient merge request. It is ok to close this merge request by another self-contained merge request.

**Comment by svettwer** [comment]
@kezhuw No worries. Pointing out this issue was a very valuable contribution! :+1: 
As I've applied a different merge strategy here, it makes sense to close this PR, as the commit  is references by a different hash this time (but is still linked to your account).

Last time, I took the PR into `master`, cherry picked the commits into `v2.7-bugfix` and merged them back into master so that master is ahead as it should. With this strategy, the original hash is preserved and the base PR is closed as well. As cherry picking is not recommendable, I avoided the cherry pick with a rebase onto `v2.7-bugfix`. This cleans up the commit history but the commit hashes are different because of the rebase.

**Pull request closed without merging**
