### PR TITLE
upgrade to spring v6.2.0

### PR DESCRIPTION
**Pull request by bbortt**

### CODE REVIEW

**Comment by bbortt** [comment]
@christophd upgrade to spring release v6.2.0. please note the small breaking changes.

**Review by christophd — APPROVED** [review]
Awesome, many thanks for the new unit tests. Would be good to add license headers to the new test classes though

**Comment by bbortt** [comment]
> Would be good to add license headers to the new test classes though

true, sorry I forgot that.

it is now done 😉

**Comment by vmeyer** [comment]
Hi,
we need this fix to be able to upgrade to spring-boot 3.4.0. 

Our citrus-http-component tests with failure scenarios do not work anymore in combination with citrus-4.4.0 because of the changes in DefaultResponseErrorHandler. The propagation mode which citrus overrides to be able to receive errors in http.client is broken because of the changed method signature in spring 6.2.0.

When do you plan to release this upgrade?

**Comment by christophd** [comment]
@vmeyer @bbortt Citrus 4.5.0 is available. Please let me know if it works for you now

**Pull request merged**
