### PR TITLE
Fixed #524 Initial local build failing in citrus-arquillian

### LINKED ISSUE #524: Initial local build failing in citrus-arquillian
**Citrus Version**
v2.7.7

**Expected behavior**
Initial local build with empty Maven repository (~/.m2/repository) should be successful

**Actual behavior**
Build fails with citrus-arquillian module because of missing dependency for 'org.yaml.snakeyaml'

**Test case sample**
Build Citrus with empty Maven repository

### PR DESCRIPTION
**Pull request by christophd**
Fixed issue #524 by adding a dependency for 'snakeyaml' in scope 'provided' to citrus-arquillian module

### CODE REVIEW

**Comment by svettwer** [comment]
Hi!
Seems like the change broke the builds. =/

I'm currently a little busy so I can't investigate in detail but it seems that the failures are not timeout related as usual.

**Comment by christophd** [comment]
The build failure is not related to my changes. Some test in the citrus-ssh module failed because of authentication issues. I can not imagine how the changes in this PR have affected those.

2nd build (manually restart) has been terminated because it took too long.

**Comment by svettwer** [comment]
That's strange :thinking: 
All builds have been successful over the lasts weeks. Can't imagine why they should become unstable.
I have to investigate this first.

**Comment by svettwer** [comment]
Hi!

I've double checked the builds and even restarted the last `v.2.7-bugfix ` branch build. The `v.2.7-bugfix ` was successful while `fix/524/initial-build-failing` is failing continuously. :thinking: 
There has to be an issue in the changes, even if it seems that it is a minor one.

**Pull request merged**
