### PR TITLE
Upgrade jetty-server to version 9.4.18.v20190429 and camel-core to version 2.23.2

### PR DESCRIPTION
**Pull request by swathisprasad**

### CODE REVIEW

**Comment by swathisprasad** [comment]
Hi, I just upgraded the Jetty and camel-core versions to the latest.

**Comment by svettwer** [comment]
Hi!

That is awesome, thx a lot! I'm currently trying to convince Travis to build your PR as drafts are ignored by Travis at the moment. 

So it might be required to push another commit to trigger the build.

BR, 
Sven

**Comment by swathisprasad** [comment]
> Hi!
> 
> That is awesome, thx a lot! I'm currently trying to convince Travis to build your PR as drafts are ignored by Travis at the moment.
> 
> So it might be required to push another commit to trigger the build.
> 
> BR,
> Sven
Sure, I will make another commit today if the build does not get triggered. Thanks!

**Comment by svettwer** [comment]
Here is the discussion on Travis not building draft PRs currently.

https://travis-ci.community/t/draft-pull-requests-not-being-built/2434/10

**Comment by swathisprasad** [comment]
Updating camel-core to version 2.23.2 is causing some tests to fail. I will look into it and create a separate pull request.

**Comment by svettwer** [comment]
Awesome, thx! :tada: 

As this fix should also be included in the 2.7-bugfix branch, I'll rebase your changes and merge them manually.

BR,
Sven

**Comment by swathisprasad** [comment]
Awesome, thanks Sven!

**Comment by svettwer** [comment]
Hi!

I've [merged your changes](https://github.com/citrusframework/citrus/compare/d41f66614461...6a47ecec0334) into master via the v2.7-bugfix branch. Again, thx a lot for your help! :tada: 

As I had to rebase the changes, the hashes created by git are different from yours. That causes that git is unable to detect that your changes have been merged. So please don't be confused that I have now close this PR instead of merging it. :wink: 

BR,
Sven

**Comment by swathisprasad** [comment]
Hi Sven, 

Thanks a lot for the merge!

Best Regards,
Swathi

**Pull request closed without merging**
