### PR TITLE
remove code smells

### PR DESCRIPTION
**Pull request by bbortt**
removed some code "smells"...
* unused imports
* unnecessary assignments or initializations
* usages of `Arrays#asList` with single arguments
* inner classes that weren't static

additionally:
* [close all autocloseables using try-with-resource statements](https://github.com/citrusframework/citrus/commit/652acff12edd7f0c7a85d28df9a43b952d5149c5)

### CODE REVIEW

**Comment by bbortt** [comment]
ok, sorry. this requires some more work.

**Review by christophd — APPROVED** [review]
LGTM thanks

**Comment by bbortt** [comment]
@christophd I've rebased it and fixed the merge conflicts.

**Comment by christophd** [comment]
CI job is flaky. I'll have a look

**Comment by bbortt** [comment]
@christophd let me know if you've fixed it. https://github.com/citrusframework/citrus/pull/1232 would be a good addition to the next release as well.

**Pull request merged**
