### PR TITLE
chore(deps) upgrade Maven plugins Surefire and Failsafe to 3.x

### LINKED ISSUE #933: Update to surefire/failsafe 3.0.0
Use surefire/failsafe Maven plugin 3.0.0 and see why the current build is failing with this version

### PR DESCRIPTION
**Pull request by apupier**
fixes #933

### CODE REVIEW

**Comment by christophd** [comment]
Last time I checked the unit tests were failing with surefire 3.x - let's see how the GitHub workflow goes 🤞

**Comment by apupier** [comment]
went fine locally:

```
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  03:56 min
[INFO] Finished at: 2023-08-21T15:31:49+02:00
```

**Comment by christophd** [comment]
`03:56 min` looks suspicious - too fast - unless you have a beast machine

**Comment by christophd** [comment]
yeah same for the CI job - I can see lots of

```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] 
```

**Comment by bbortt** [comment]
yep, still the same problem.

**Comment by bbortt** [comment]
@christophd did we agree on a migration to JUnit? if so, I'd sync these plugin updates with it. but I'm not sure if the work is worth it, honestly.

**Pull request closed without merging**
