### PR TITLE
fix: otherwise there will be a new line in the output

### PR DESCRIPTION
**Pull request by chokdee**

### CODE REVIEW

**Comment by svettwer** [comment]
Concerning issue #426

**Comment by chokdee** [comment]
Sorry for my mistake. Both fixes are in the same PR

**Comment by svettwer** [comment]
Hi!

I merged your changes into an up to date master based branch. The build looks promising. I'll review the changes asap.

BR,
Sven

**Comment by svettwer** [comment]
Concerning issue #432

**Pull request merged**
