### PR TITLE
chore: Update Kubernetes module

### PR DESCRIPTION
**Pull request by christophd**
- Update Kubernetes Fabric8 client to 6.10.0

### CODE REVIEW

**Comment by bbortt** [comment]
I think the copyrights on the touched classes should be updated. and if you don't mind me saying this, writing some tests would do good 😉 I can spend some if you give me time over the weekend.

**Comment by christophd** [comment]
@bbortt thanks! about the copyright year. How about removing the year information completely? it does not give too much information because you can always have a look into the GitHub history when a file has been added

**Comment by bbortt** [comment]
ahm yea. but isn't it necessary to comply with the license? that each file must mention the licensing? I am no lawyer, but that's how I always understood it.

**Comment by christophd** [comment]
Yeah right, I did not mean to remove the license header. just the copyright year information that needs to be adjusted every time

**Comment by christophd** [comment]
I have enabled the integration tests now with using the Fabric8 mock K8s server

**Pull request merged**
