### PR TITLE
(#451) Changed path creation in 'getTestFiles()' method and altered/f…

### PR DESCRIPTION
**Pull request by mischcon**
…ixed tests

### CODE REVIEW

**Comment by svettwer** [comment]
Hi!

Thx for proposing the PR! I'll review it asap in detail. When I briefly reviewed the changes, I recognized, that you haven't added any tests verifying your fix. 
It would be great if you could add some. If you have no time for that, I'll add them later in the review.
Anyways: Thx for you help! =)

BR,
Sven

**Comment by mischcon** [comment]
Hi!

I added some tests, but I am not quite sure how to test this issue, so please feel free to push me in the right direction in case something is missing / incorrect :)

**Comment by svettwer** [comment]
Hi!

The changes look good. I've added a Test for the `AbstractTestDocsGenerator` that ensures that `getTestFiles` finds a dummy file. This should be enough for this case, I think.

I've also rebased your changes to the `v.2.7-bugfix` branch. This is nothing that you could have known. It's more our fault not providing a detailed contribution guideline.

Thx a lot for your contribution. I'll merge as soon as the travis build is done.

BR,
Sven

**Comment by svettwer** [comment]
Hi!

Your changes are merged now. This is not represented by the PR due to the rebase unfortunately. Thx again!

BR,
Sven

**Pull request closed without merging**
