### PR TITLE
varargs bug fix

### PR DESCRIPTION
**Pull request by blessedchitamba**
Root issue: https://github.com/citrusframework/citrus/issues/1008

### CODE REVIEW

**Comment by christophd** [comment]
@blessedchitamba thanks! could you please squash your commits. the PR contains some unnecessary noise commits. Many thanks!

**Comment by bbortt** [comment]
@christophd you can select "squash and merge" on github using the dropdown on the merge-button. I've done it.

**Comment by blessedchitamba** [comment]
I see you ended up merging and squashing yourself thank you! Do you know when I can expect the new artifact to be released? i.e. what is your release cycle?

**Comment by bbortt** [comment]
v4.0.0 coming soon.. see #922 for more information.

**Comment by blessedchitamba** [comment]
Hi Tim,

Just wanted to ask, does Citrus offer methods in the send test action that allow for sending of byte arrays? I see there is allowance for byte stream validation etc. and I am not sure if that's the one I should be using.

Kind regards,
Blessed
________________________________

**Comment by bbortt** [comment]
I think you can achieve this.. the mentioned "byte stream" chapter in the documentation mentions sending streams as well! see: https://citrusframework.org/citrus/reference/html/index.html#binary-stream-message-validation;

> By the way sending binary messages in Citrus is also very easy. [...]

let me know if that caused any problems on your side!

**Pull request merged**
