### PR TITLE
Update camel-core to version 2.23.2

### PR DESCRIPTION
**Pull request by swathisprasad**

### CODE REVIEW

**Comment by swathisprasad** [comment]
Hi, 
I could upgrade camel-core to version 2.23.2.

**Comment by svettwer** [comment]
Hi!

Looks good to me so far. :+1: 
I'm just a little curious why your first PR had some failing tests after the camel update while the version has not been changed in this one. :thinking: 
Nevertheless, I will rebase this change again onto v2.7-bugfix and merge it into master afterwards. As for the last of your PRs, I will have to close it manually as the rebase changes the hashes of the commits.

To avoid the rebase, you could start developing from the branch `v2.7-bugfix` the next time you fix a bug or perform a security update. More information can be found in the [contribution guidelines](https://github.com/citrusframework/citrus/blob/master/CONTRIBUTING.md).

BR,
Sven

**Comment by swathisprasad** [comment]
Hi Sven,

Thanks for merging and I will check for guidelines. I was also surprised that build was successful this time. It could be that version change did not cause the build to fail at all. 

Best Regards,
Swathi

**Comment by svettwer** [comment]
Hi!

I just found out that the issue was caused by `com.consol.citrus.TestCaseTest.testThreadLeak`. Unfortunately in some situation the build becomes unstable because of this and some other tests. This is something we try to improve over time but it seems that your PR has been affected by such a _"flaky"_ test. Sorry for that!

BTW: The bugfix and master build passed successfully. Therefore I will close this PR.

BR,
Sven

**Comment by swathisprasad** [comment]
Thanks for letting me know.

**Pull request closed without merging**
